CUDA_VISIBLE_DEVICES=0 python dpo_training.py \
    --model_name_or_path /root/autodl-tmp/models/Qwen2.5-7B-Instruct/qwen/Qwen2___5-7B-Instruct \
    --tokenizer_name_or_path /root/autodl-tmp/models/Qwen2.5-7B-Instruct/qwen/Qwen2___5-7B-Instruct \
    --peft_path /root/autodl-tmp/outputs-sft-medical-qwen-7b/checkpoint-1876 \
    --template_name qwen \
    --train_file_dir /root/autodl-tmp/data/reward \
    --validation_file_dir /root/autodl-tmp/data/reward \
    --per_device_train_batch_size 1 \
    --gradient_accumulation_steps 16 \
    --per_device_eval_batch_size 1 \
    --do_train \
    --do_eval \
    --use_peft True \
    --max_train_samples 6000 \
    --max_eval_samples 300 \
    --max_steps 250 \
    --eval_steps 50 \
    --save_steps 100 \
    --max_source_length 512 \
    --max_target_length 256 \
    --output_dir /root/autodl-tmp/outputs-dpo-medical-qwen-7b \
    --target_modules all \
    --lora_rank 16 \
    --lora_alpha 32 \
    --lora_dropout 0.05 \
    --learning_rate 2e-4 \
    --torch_dtype bfloat16 \
    --bf16 True \
    --fp16 False \
    --device_map auto \
    --report_to tensorboard \
    --remove_unused_columns False \
    --gradient_checkpointing True \
    --flash_attn True \
    --cache_dir /root/autodl-tmp/cache